### PR TITLE
correct rotation Jacobians

### PR DESCRIPTION
**Pull request by JzHuai0108**
I think the rotation Jacobians should be corrected.

### CODE REVIEW

**Comment by koide3** [comment]
Thanks for your PR. As you pointed out, the current implementation has inconsistency of the derivatives (SE3) and the retraction operation (SO3 + trans). I think it may be better to change the retraction to SE3 instead of changing the derivatives for better convergence. Do you have any opinions?

https://github.com/SMRT-AIST/fast_gicp/blob/bb36054112eba442772a5c4781835499e9cd7426/include/fast_gicp/gicp/impl/lsq_registration_impl.hpp#L140C3-L140C3

**Comment by JzHuai0108** [comment]
From the cited line in the link, the codebase uses the SO3+trans error formulation. 
I personally root for this formulation because
the se3 error formulation though seemingly elegant is quite involved and does not show performance gain.

**Comment by koide3** [comment]
Sorry for the late response. I will do a quick test for SE3 and SO3+trans formulations in a few days, and merge this PR if SO3+trans shows the same or better result than that of the other one.

**Comment by koide3** [comment]
I implemented SE3 expmap and did a quick comparison of the SE3 and SO3 + trans formulations on the KITTI dataset. It seems the SE3 formulation shows a slightly better convergence compared to SO3. So, I would like to close this PR and open a new PR to integrate the SE3 expmap instead.

so3_vs_se3

**Pull request closed without merging**
